name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

# instalando versão do .Net
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

# executando build da aplicacao
    - name: Build with dotnet
      run: dotnet build --configuration Release

# executa os testes
    - name: Test
      run: dotnet test

#criando o pacote
    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Publish
      run: dotnet nuget push "Decompositor/bin/Release/*.nupkg" -k ${{ secrects.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
